# Generated by Django 6.0.3 on 2026-03-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='available_tickets',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='event',
            name='total_tickets',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
